# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.4.dev0+gc5dd368.d20230307'
__version_tuple__ = version_tuple = (0, 0, 4, 'dev0', 'gc5dd368.d20230307')
